KutuphaneProgrami/KutuphaneProgrami/Controllers/BorrowBooksController.cs
using BusinessLayer.Concrete;
using DataAccesLayer.EntityFramework;
using EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KutuphaneProgrami.Controllers
{
    [Authorize(Roles = "A")]
    public class BorrowBooksController : Controller
    {
        UserManager um = new UserManager(new EfUserDal());
        BookManager bm = new BookManager(new EfBookDal());
        BorrowManager brm = new BorrowManager(new EfBorrowDal());
        RequestManager rn = new RequestManager(new EfRequestDal());
        public ActionResult BookBorrow()
        {
            var bookvalues = brm.GetList();
            return View(bookvalues);
        }
        public ActionResult BringBook()
        {
            return View();
        }
        public ActionResult GiveBook()
        {
            List<SelectListItem> userinfo = (from x in um.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.UserName+" "+ x.UserSurname,
                                                      Value = x.Id.ToString()
                                                  }).ToList();
            List<SelectListItem> bookinfo = (from x in bm.GetList()
                                             select new SelectListItem
                                             {
                                                 Text = x.BookName,
                                                 Value = x.Id.ToString()
                                             }).ToList();
            ViewBag.users = userinfo;
            ViewBag.books = bookinfo;
            return View();
        }
        [HttpGet]
        public ActionResult AddBorrow()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddBorrow(Borrow p)
        {
            brm.BorrowAdd(p);
            p.IsCome = false;
            return RedirectToAction("BookBorrow");
        }
        public ActionResult BorrowUpdate(int id)
        {
            List<SelectListItem> userinfo = (from x in um.GetList()
                                             select new SelectListItem
                                             {
                                                 Text = x.UserName + " " + x.UserSurname,
                                                 Value = x.Id.ToString()
                                             }).ToList();
            List<SelectListItem> bookinfo = (from x in bm.GetList()
                                             select new SelectListItem
                                             {
                                                 Text = x.BookName,
                                                 Value = x.Id.ToString()
                                             }).ToList();
            ViewBag.users = userinfo;
            ViewBag.books = bookinfo;
            var bookvalue = brm.GetByID(id);
            return View(bookvalue);
        }
        [HttpPost]
        public ActionResult BorrowUpdate(Borrow p)
        {
            brm.BorrowUpdate(p);
            return RedirectToAction("BookBorrow");
        }
        public ActionResult IsCome(int id)
        {
            var borrowvalue= brm.GetByID(id);
            borrowvalue.IsCome = true;
            brm.BorrowUpdate(borrowvalue);
            return RedirectToAction("BookBorrow");
        }
        public ActionResult RequestBorrow()
        {
            var values = rn.GetList();
            return View(values);
        }
        public ActionResult RequestApprove(int id)
        {
            var request = rn.GetByID(id);
            return View(request);
        }
    }
}

KutuphaneProgrami/KutuphaneProgrami/Views/BorrowBooks/BookBorrow.cshtml
@using EntityLayer
@model List<Borrow>
@{
    ViewBag.Title = "Ödünç Verilen Kitaplar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<a href="/BorrowBooks/GiveBook" class="btn btn-success" id="btn1">Kitap Ver</a>
<br /><br />
<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>Kitap Adı</th>
            <th>Kitabı Alan Üye</th>
            <th>Aldığı Tarih</th>
            <th>Getireceği Tarih</th>
            <th>Güncelle</th>
            <th>Getirildi Olarak İşaretle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.IsCome == false)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Book.BookName</td>
                    <td>@item.User.UserName @item.User.UserSurname</td>
                    <td>@item.BorrowDate</td>
                    <td>@item.BringDate</td>
                    <td><a href="/BorrowBooks/BorrowUpdate/@item.Id" class="btn btn-warning">Güncelle</a></td>
                    <td><a href="/BorrowBooks/IsCome/@item.Id" class="btn btn-success">Getirdi Olarak İşaretle</a></td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <th>Id</th>
            <th>Kitap Adı</th>
            <th>Kitabı Alan Üye</th>
            <th>Aldığı Tarih</th>
            <th>Getireceği Tarih</th>
            <th>Güncelle</th>
            <th>Getirildi Olarak İşaretle</th>
        </tr>
    </tfoot>
</table>
<style>
    .modal {
        text-align: center;
        padding: 0 !important;
    }

        .modal:before {
            content: '';
            display: inline-block;
            height: 100%;
            vertical-align: middle;
            margin-right: -4px;
        }

    .modal-dialog {
        display: inline-block;
        text-align: left;
        vertical-align: middle;
    }
    #btn1 {
        position: relative;
        right: -1475px;
    }
</style>

KutuphaneProgrami/KutuphaneProgrami/Views/BorrowBooks/BorrowUpdate.cshtml
@model EntityLayer.Borrow
@{
    ViewBag.Title = "Ödünç Kitap Güncelleme";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("BorrowUpdate", "BorrowBooks", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.Id, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Adı")
    @Html.DropDownListFor(x => x.UserId, (List<SelectListItem>)ViewBag.users, new { @class = "form-control" })
    <br />
    @Html.Label("Yazar Adı")
    @Html.DropDownListFor(x => x.BookId, (List<SelectListItem>)ViewBag.books, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(model => model.BorrowDate, new { @type = "date", @class = "form-control" })
    <br />
    @Html.TextBoxFor(model => model.BringDate, new { @type = "date", @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
}

KutuphaneProgrami/KutuphaneProgrami/Views/BorrowBooks/GiveBook.cshtml
@using EntityLayer
@model EntityLayer.Borrow
@{
    ViewBag.Title = "Ödünç Kitap Ver";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form action="/BorrowBooks/AddBorrow" method="post">
    <div class="form-group">
        @Html.HiddenFor(x => x.Id)
        @Html.Label("Verilen Üye")
        <br />
        @Html.DropDownListFor(x => x.UserId, (List<SelectListItem>)ViewBag.users, new { @class = "form-control"})
        <br />
        @Html.Label("Verilen Kitap")
        @Html.DropDownListFor(x => x.BookId, (List<SelectListItem>)ViewBag.books, new { @class = "form-control" })
        <br />
        @Html.Label("Kitabı Alacağı Tarih")
        @Html.TextBoxFor(model => model.BorrowDate, new { @type = "date", @class = "form-control" })
        <br />
        @Html.Label("Kitabı Vereceği Tarih")
        @Html.TextBoxFor(model => model.BringDate, new { @type = "date", @class = "form-control" })
        <br />

        <button class="btn btn-info">Ekle</button>
    </div>
</form>

KutuphaneProgrami/KutuphaneProgrami/Views/BorrowBooks/RequestApprove.cshtml
@using EntityLayer
@model EntityLayer.BorrowRequest
@{
    ViewBag.Title = "İsteği Onayla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddBorrow", "BorrowBooks", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.Id, new { @class = "form-control"})
    @Html.HiddenFor(x => x.UserId, new { @class = "form-control"})
    @Html.HiddenFor(x => x.BookId, new { @class = "form-control"})
    <br />
    @Html.Label("Verilen Üye")
    <br />
    @Html.TextBoxFor(x => x.User.Id, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.Label("Verilen Kitap")
    @Html.TextBoxFor(x => x.Book.BookName, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.Label("Getireceği Tarih")
    @Html.TextBoxFor(x => x.BorrowDate, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.Label("Geleceği Tarih")
    @Html.TextBoxFor(x => x.BringDate, new { @class = "form-control", @readonly = "readonly" })
    <br />
    <button class="btn btn-success">Onayla</button>
</div>
}

KutuphaneProgrami/KutuphaneProgrami/Views/BorrowBooks/RequestBorrow.cshtml
@using EntityLayer
@model List<BorrowRequest>
@{
    ViewBag.Title = "Ödünç Alma İstekleri";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>İsteyen Kişi</th>
            <th>Kitap Adı</th>
            <th>İstenilen Tarih</th>
            <th>Getirilecek Tarih</th>
            <th>Durum</th>
            <th>Onayla</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.User.UserName @item.User.UserSurname</td>
                <td>@item.Book.BookName</td>
                <td>@item.BorrowDate</td>
                <td>@item.BringDate</td>
                @if (item.Given == true)
                {
                    <td>Verildi</td>
                }
                else
                {
                    <td>Beklemede</td>
                }
                <td><a class="btn btn-success" href="/BorrowBooks/RequestApprove/@item.Id">Ekle</a></td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>Id</th>
            <th>İsteyen Kişi</th>
            <th>Kitap Adı</th>
            <th>İstenilen Tarih</th>
            <th>Getirilecek Tarih</th>
            <th>Durum</th>
            <th>Onayla</th>
        </tr>
    </tfoot>
</table>