KutuphaneProgrami/KutuphaneProgrami/Controllers/BookController.cs
using BusinessLayer.Concrete;
using DataAccesLayer;
using DataAccesLayer.EntityFramework;
using EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KutuphaneProgrami.Controllers
{
    [Authorize(Roles = "A")]
    public class BookController : Controller
    {
        Context c = new Context();
        BookManager bm = new BookManager(new EfBookDal());
        WriterManager wm = new WriterManager(new EfWriterDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        public ActionResult Index()
        {
            var bookvalues = bm.GetList();
            return View(bookvalues);
        }
        [HttpGet]
        public ActionResult AddBook()
        {
            List<SelectListItem> categoryvalue = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.Id.ToString()
                                                  }).ToList();
            List<SelectListItem> writervalue = (from x in wm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.WriterName + " " +x.WriterSurname,
                                                      Value = x.Id.ToString()
                                                  }).ToList();
            ViewBag.ctg = categoryvalue;
            ViewBag.writer = writervalue;
            return View();
        }
        [HttpPost]
        public ActionResult AddBook(Book p)
        {
            p.BookAddDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.Status = true;
            bm.BookAdd(p);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult BookUpdate(int id)
        {
            List<SelectListItem> categoryvalue = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.Id.ToString()
                                                  }).ToList();
            List<SelectListItem> writervalue = (from x in wm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName + " " + x.WriterSurname,
                                                    Value = x.Id.ToString()
                                                }).ToList();
            ViewBag.ctg = categoryvalue;
            ViewBag.writer = writervalue;
            var bookvalue = bm.GetByID(id);
            return View(bookvalue);
        }
        [HttpPost]
        public ActionResult BookUpdate(Book p)
        {
            bm.BookUpdate(p);
            return RedirectToAction("Index");
        }
        public ActionResult ActiveOrPassive(int id)
        {
            var bookvalue = bm.GetByID(id);

            if (bookvalue.Status == true)
            {
                bookvalue.Status = false;
            }
            else
            {
                bookvalue.Status = true;
            }
            bm.BookUpdate(bookvalue);
            return RedirectToAction("Index");
        }
    }
}

KutuphaneProgrami/KutuphaneProgrami/Controllers/UserPanelController.cs
using BusinessLayer.Concrete;
using DataAccesLayer;
using DataAccesLayer.EntityFramework;
using EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace KutuphaneProgrami.Controllers
{
    public class UserPanelController : Controller
    {
        Context c = new Context();
        UserManager um = new UserManager(new EfUserDal());
        BookManager bm = new BookManager(new EfBookDal());
        BorrowManager brm = new BorrowManager(new EfBorrowDal());
        RequestManager rn = new RequestManager(new EfRequestDal());
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MyProfile(string p)
        {
            p = (string)Session["UserMail"];
            var useridinfo = c.Users.Where(x => x.UserMail == p).Select(y => y.Id).FirstOrDefault();
            var uservalues = um.GetListById(useridinfo);
            ViewBag.userid = useridinfo;
            return View(uservalues);
        }
        [HttpGet]
        public ActionResult UserUpdate(int id)
        {
            string p = (string)Session["UserMail"];
            var useridinfo = c.Users.Where(x => x.UserMail == p).Select(y => y.Id).FirstOrDefault();
            var uservalue = um.GetByID(useridinfo);
            return View(uservalue);
        }
        [HttpPost]
        public ActionResult UserUpdate(User p)
        {
            SHA1 sha1 = new SHA1CryptoServiceProvider();
            string writerpassword = p.UserPassword;
            string result = Convert.ToBase64String(sha1.ComputeHash(Encoding.UTF8.GetBytes(writerpassword)));
            p.UserPassword = result;
            string k = (string)Session["UserMail"];
            var userroleinfo = c.Users.Where(x => x.UserMail == k).Select(y => y.Role).FirstOrDefault();
            p.Role = userroleinfo;
            um.UserUpdate(p);
            return RedirectToAction("MyProfile");
        }
        public ActionResult Books()
        {
            var books = bm.GetList();
            return View(books);
        }
        [HttpGet]
        public ActionResult MyBorrowBooks()
        {
            string p = (string)Session["UserMail"];
            var useridinfo = c.Users.Where(x => x.UserMail == p).Select(y => y.Id).FirstOrDefault();
            var deneme = c.Borrows.ToList().Where(x => x.UserId == useridinfo).ToList();
            return View(deneme);
        }
        public ActionResult BorrowRequest()
        {
            string p = (string)Session["UserMail"];
            var useridinfo = c.Users.Where(x => x.UserMail == p).Select(y => y.Id).FirstOrDefault();
            var values = c.BorrowRequests.ToList().Where(x => x.UserId == useridinfo).ToList();
            return View(values);
        }
        [HttpGet]
        public ActionResult BorrowRequestAdd()
        {
            List<SelectListItem> bookinfo = (from x in bm.GetList()
                                             select new SelectListItem
                                             {
                                                 Text = x.BookName,
                                                 Value = x.Id.ToString()
                                             }).ToList();
            ViewBag.books = bookinfo;
            return View();
        }
        [HttpPost]
        public ActionResult BorrowRequestAdd(BorrowRequest p)
        {
            string v = (string)Session["UserMail"];
            var useridinfo = c.Users.Where(x => x.UserMail == v).Select(y => y.Id).FirstOrDefault();
            p.UserId = useridinfo;
            rn.BorrowRequestAdd(p);
            return RedirectToAction("BorrowRequest");
        }
    }
}

KutuphaneProgrami/KutuphaneProgrami/Views/UserPanel/Books.cshtml
@using EntityLayer
@model List<Book>
@{
    ViewBag.Title = "Kitaplar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>Sıra No</th>
            <th>Kategori</th>
            <th>Kitap Adı</th>
            <th>Adet</th>
            <th>Yazar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.Status==true)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.BookNo</td>
                    <td>
                        @item.Categories.CategoryName
                    </td>
                    <td>@item.BookName</td>
                    <td>@item.Total</td>
                    <td>@item.Writer.WriterName @item.Writer.WriterSurname</td>
                </tr>
            }

        }

    </tbody>
    <tfoot>
        <tr>
            <th>Id</th>
            <th>Sıra No</th>
            <th>Kategori</th>
            <th>Kitap Adı</th>
            <th>Adet</th>
            <th>Yazar</th>
        </tr>
    </tfoot>
</table>
<style>
    .modal {
        text-align: center;
        padding: 0 !important;
    }

        .modal:before {
            content: '';
            display: inline-block;
            height: 100%;
            vertical-align: middle;
            margin-right: -4px;
        }

    .modal-dialog {
        display: inline-block;
        text-align: left;
        vertical-align: middle;
    }
</style>

KutuphaneProgrami/KutuphaneProgrami/Views/UserPanel/BorrowRequest.cshtml
@using EntityLayer
@model List<BorrowRequest>
@{
    ViewBag.Title = "Ödünç Alma İsteklerim";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>Kitap Adı</th>
            <th>İstenilen Tarih</th>
            <th>Getirilecek Tarih</th>
            <th>Durum</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.Id</td>
            <td>@item.Book.BookName</td>
            <td>@item.BorrowDate</td>
            <td>@item.BringDate</td>
            @if (item.Given == true)
            {
                <td>Verildi</td>
            }
            else
            {
                <td>Beklemede</td>
            }
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>Id</th>
            <th>Kitap Adı</th>
            <th>İstenilen Tarih</th>
            <th>Getirilecek Tarih</th>
            <th>Durum</th>
        </tr>
    </tfoot>
</table>

KutuphaneProgrami/KutuphaneProgrami/Views/UserPanel/BorrowRequestAdd.cshtml
@using EntityLayer
@model EntityLayer.BorrowRequest
@{
    ViewBag.Title = "Ödünç Alma İsteği Oluştur";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form action="/UserPanel/BorrowRequestAdd" method="post">
    <div class="form-group">
        @Html.HiddenFor(x => x.Id)
        @Html.Label("İstenilen Kitap")
        @Html.DropDownListFor(x => x.BookId, (List<SelectListItem>)ViewBag.books, new { @class = "form-control" })
        <br />
        @Html.Label("Kitabı Alacağanız Tarih")
        @Html.TextBoxFor(model => model.BorrowDate, new { @type = "date", @class = "form-control" })
        <br />
        @Html.Label("Kitabı Geri Vereceğiniz Tarih")
        @Html.TextBoxFor(model => model.BringDate, new { @type = "date", @class = "form-control" })
        <br />

        <button class="btn btn-info">Ekle</button>
    </div>
</form>

KutuphaneProgrami/KutuphaneProgrami/Views/UserPanel/MyBorrowBooks.cshtml
@using EntityLayer
@model List<Borrow>
@{
    ViewBag.Title = "Ödünç Aldığım Kitaplar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>Kitap Adı</th>
            <th>Kitabı Alan Üye</th>
            <th>Aldığı Tarih</th>
            <th>Getireceği Tarih</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)    
        {
            if (item.IsCome == false)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Book.BookName</td>
                    <td>@item.User.UserName @item.User.UserSurname</td>
                    <td>@item.BorrowDate</td>
                    <td>@item.BringDate</td>
                </tr>
            }
        }
    </tbody>
    <tfoot>
        <tr>
            <th>Id</th>
            <th>Kitap Adı</th>
            <th>Kitabı Alan Üye</th>
            <th>Aldığı Tarih</th>
            <th>Getireceği Tarih Tarih</th>
        </tr>
    </tfoot>
</table>
<style>
    .modal {
        text-align: center;
        padding: 0 !important;
    }

        .modal:before {
            content: '';
            display: inline-block;
            height: 100%;
            vertical-align: middle;
            margin-right: -4px;
        }

    .modal-dialog {
        display: inline-block;
        text-align: left;
        vertical-align: middle;
    }

    #btn1 {
        position: relative;
        right: -1475px;
    }
</style>

KutuphaneProgrami/KutuphaneProgrami/Views/UserPanel/MyProfile.cshtml
@using EntityLayer
@model List<User>
@{
    ViewBag.Title = "Profilim";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@foreach (var item in Model)
{
    <div class="col-md-3">
        <h4>Üye Adı Soyadı</h4>
        <label>@item.UserName @item.UserSurname</label>
        <br />
        <h4>Üye Tc Kimlik Numarası</h4>
        <label>@item.UserIdNumber</label>
        <br />
        <h4>Üye Telefon Numarası</h4>
        <label>@item.UserPhone</label>
        <br />
        <h4>Kayıt Tarihi</h4>
        <label>@item.SignDate</label>
        <br />
        <h4>Üye Durumu</h4>
        @if (item.UserStatus == true)
        {
            <label>Aktif</label>
            <br />
        }
        else
        {
            <label>Pasif</label>
            <br />
        }
        <h4>Üye Yetkisi</h4>
        @if (item.Role == "A")
        {
            <label>Admin</label>
            <br />
        }
        else
        {
            <label>Üye</label>
            <br />
        }
    </div>
}
<div class="col-md-9">
    <a href="/UserPanel/UserUpdate/@ViewBag.userid" class="btn btn-info">Profili Düzenle</a>
</div>

KutuphaneProgrami/KutuphaneProgrami/Views/UserPanel/UserUpdate.cshtml
@model EntityLayer.User
@{
    ViewBag.Title = "Profil Güncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("UserUpdate", "UserPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.Id, new { @class = "form-control" })
        @Html.HiddenFor(x => x.SignDate, new { @class = "form-control" })
        @Html.HiddenFor(x => x.UserPassword, new { @class = "form-control" })
        @Html.HiddenFor(x => x.Penalty, new { @class = "form-control" })
        @Html.HiddenFor(x => x.UserStatus, new { @class = "form-control" })
        <br />
        @Html.Label("Üye Adı")
        @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
        <br />
        @Html.Label("Üye Soyadı")
        @Html.TextAreaFor(x => x.UserSurname, new { @class = "form-control" })
        <br />
        @Html.Label("Üye Tc Kimlik Numarası")
        @Html.TextAreaFor(x => x.UserIdNumber, new { @class = "form-control" })
        <br />
        @Html.Label("Üye Telefon Numarası")
        @Html.TextAreaFor(x => x.UserPhone, new { @class = "form-control" })
        <br />
        @Html.Label("Üye Mail")
        @Html.TextAreaFor(x => x.UserMail, new { @class = "form-control" })
        <br />
        @Html.Label("Üye Şifre")
        @Html.TextAreaFor(x => x.OriginalPass, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}