KutuphaneProgrami/KutuphaneProgrami/Controllers/StatisticController.cs
using BusinessLayer.Concrete;
using DataAccesLayer;
using DataAccesLayer.EntityFramework;
using KutuphaneProgrami.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KutuphaneProgrami.Controllers
{
    [Authorize(Roles = "A")]
    public class StatisticController : Controller
    {
        BookManager bm = new BookManager(new EfBookDal());
        UserManager um = new UserManager(new EfUserDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());

        // GET: Statistic
        public ActionResult Index()
        {
            var bookcount = bm.GetList().Count(x=>x.Status==true);
            ViewBag.book = bookcount;
            var usercount = um.GetList().Count(x => x.UserStatus == true);
            ViewBag.user = usercount;
            var categorycount = cm.GetList().Count(x => x.Status == true);
            ViewBag.category = categorycount;
            var writercount = wm.GetList().Count(x => x.Status == true);
            ViewBag.writer = writercount;
            return View();
        }
        public List<CategoryChart> CategoryList()
        {
            List<CategoryChart> writerCharts = new List<CategoryChart>();
            using (var context = new Context())
            {
                writerCharts = context.Categories.Select(c => new CategoryChart
                {
                    CategoryName = c.CategoryName,
                    BookCount = c.Books.Count()
                }).ToList();
            }

            return writerCharts;
        }

        public ActionResult CategoryChar()
        {
            return Json(CategoryList(), JsonRequestBehavior.AllowGet);
        }
    }
}

KutuphaneProgrami/KutuphaneProgrami/Views/Statistic/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("CategoryChar", "Statistic")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Category');
            data.addColumn('number', 'Kitap Sayısı');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.CategoryName, obj.BookCount]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Kategori-Kitap Grafiği",
                width: "100%",
                height: 940,
                bar: { groupWidth: "30%" },
            };
            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('Piechart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<div class="row">
    <div class="col-lg-3 col-sm-3 col-xs-12">
        <div class="white-box analytics-info">
            <h3 class="box-title">Kitap Sayısı</h3>
            <ul class="list-inline two-part">
                <li>
                    <div id="sparklinedash"></div>
                </li>
                <li class="text-right"><i class="text-success"></i> <span class="counter text-success">@ViewBag.book</span></li>
            </ul>
        </div>
    </div>
    <div class="col-lg-3 col-sm-3 col-xs-12">
        <div class="white-box analytics-info">
            <h3 class="box-title">Üye Sayısı</h3>
            <ul class="list-inline two-part">
                <li>
                    <div id="sparklinedash2"></div>
                </li>
                <li class="text-right"><i class="text-purple"></i> <span class="counter text-purple">@ViewBag.user</span></li>
            </ul>
        </div>
    </div>
    <div class="col-lg-3 col-sm-3 col-xs-12">
        <div class="white-box analytics-info">
            <h3 class="box-title">Kategori Sayısı</h3>
            <ul class="list-inline two-part">
                <li>
                    <div id="sparklinedash3"></div>
                </li>
                <li class="text-right"><i class="text-info"></i> <span class="counter text-info">@ViewBag.category</span></li>
            </ul>
        </div>
    </div>
    <div class="col-lg-3 col-sm-3 col-xs-12">
        <div class="white-box analytics-info">
            <h3 class="box-title">Yazar Sayısı</h3>
            <ul class="list-inline two-part">
                <li>
                    <div id="sparklinedash4"></div>
                </li>
                <li class="text-right"><i class="text-danger"></i> <span class="text-danger">@ViewBag.writer</span></li>
            </ul>
        </div>
    </div>
</div>

<div id="Piechart_div"></div>

@section script{
    <script src="~/Scripts/jquery.charts-sparkline.js"></script>
    <script src="~/Scripts/jquery.sparkline.min.js"></script>
    <script src="~/Scripts/jQuery.style.switcher.js"></script>
}